### PR TITLE
Add Arm64 support

### PR DESCRIPTION
**Pull request by rail**

### CODE REVIEW

**Comment by rail** [comment]
Do not merge until 22.2.0 is stable

**Comment by rail** [comment]
This is what `make VERSION=v22.2.0-beta.5 PRODUCT=cockroach` produces:

```diff
diff --git a/Formula/cockroach.rb b/Formula/cockroach.rb
index 3f4891c..c9b8f24 100644
--- a/Formula/cockroach.rb
+++ b/Formula/cockroach.rb
@@ -4,9 +4,17 @@
 class Cockroach < Formula
   desc "Distributed SQL database"
   homepage "https://www.cockroachlabs.com"
-  url "https://binaries.cockroachdb.com/cockroach-v22.1.10.darwin-10.9-amd64.tgz"
-  version "22.1.10"
-  sha256 "8cb517a56831f0b2814220cf53d480d64ed6b8ddf890890f5c7dd9ba3eab7139"
+  version "22.2.0-beta.5"
+  on_macos do
+    on_intel do
+      url "https://binaries.cockroachdb.com/cockroach-v22.2.0-beta.5.darwin-10.9-amd64.tgz"
+      sha256 "71cc8ecb35a9d8b248ea5277684fc29ca280a5f682dc6e699b1b64b3cc316afa"
+    end
+    on_arm do
+      url "https://binaries.cockroachdb.com/cockroach-v22.2.0-beta.5.darwin-11.0-aarch64.tgz"
+      sha256 "eed5bd772cc6786c1b176c149e05e236889d7a3acdceded4752ef32a52a39fe6"
+    end
+  end
 
   def install
     bin.install "cockroach"
```

**Review by celiala — APPROVED** [review]
Thanks for doing - LGTM!

**Comment by kenliu-crl** [comment]
I think we can merge this now, if I'm not mistaken?

**Comment by rail** [comment]
> I think we can merge this now, if I'm not mistaken?

We still have at least one scheduled 22.1 release before we ship 22.2.0. Ideally we can merge this after Nov 14, but I'd keep it hanging here until we are sure there is no extraordinary 22.1 release.

Maybe there is way to specify that arm is supported only for versions >= 22.2.0 🤔

**Comment by rail** [comment]
I think it's time to merge! It won't add a new platform until we regenerate the files on Dec 6.

**Pull request merged**
